# To run all pre-commit checks, use:
#
#     pre-commit run -a
#
# To install pre-commit hooks that run every time you commit:
#
#     pre-commit install
#

ci:
  autoupdate_commit_msg: "⬆️🪝 update pre-commit hooks"
  autoupdate_schedule: quarterly
  autofix_commit_msg: "🎨 pre-commit fixes"

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.22
    hooks:
      - id: uv-lock

  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # Handling unwanted unicode characters
  - repo: https://github.com/sirosen/texthooks
    rev: 0.7.1
    hooks:
      - id: fix-ligatures
      - id: fix-smartquotes

  # Check for common mistakes
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  # Check for license headers
  - repo: https://github.com/emzeat/mz-lictools
    rev: v2.8.0
    hooks:
      - id: license-tools

  # Python linting using ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args: ["--fix", "--show-fixes"]
        require_serial: true
      - id: ruff-format

  # Format configuration files with prettier
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]

  # Check for spelling
  - repo: https://github.com/crate-ci/typos
    rev: v1.36.2
    hooks:
      - id: typos

  # Catch common capitalization mistakes
  - repo: local
    hooks:
      - id: disallow-caps
        name: Disallow improper capitalization
        language: pygrep
        entry: PyBind|Numpy|Cmake|CCache|Github|PyTest|Mqt|Tum|MQTopt|MQTref
        exclude: .pre-commit-config.yaml

  # Check JSON schemata
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.0
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-readthedocs

  # Check the pyproject.toml file
  - repo: https://github.com/henryiii/validate-pyproject-schema-store
    rev: 2025.09.12
    hooks:
      - id: validate-pyproject
